- name: Pull and Run docker image
  hosts: all
  tasks:
    - name: Pull agamkashyap/scientific_calc
      docker_image:
        name: agamkashyap/scientific_calc
        source: pull
      var:
        ansible_python_interpreter: /home/linuxbrew/.linuxbrew/bin/python3
